//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineClub_TuPeliculaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class actor
    {
        public actor()
        {
            this.pelicula_actor = new HashSet<pelicula_actor>();
        }
    
        public int id_actor { get; set; }
        public string nombre { get; set; }
        public Nullable<int> FK_id_nacionalidad { get; set; }
        public Nullable<int> FK_id_genero { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public Nullable<int> anios_experiencia { get; set; }
        public Nullable<int> nro_premios { get; set; }
        public string sexo { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual genero genero { get; set; }
        public virtual nacionalidad nacionalidad { get; set; }
        public virtual ICollection<pelicula_actor> pelicula_actor { get; set; }
    }
}
