//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineClub_TuPeliculaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alquiler
    {
        public alquiler()
        {
            this.detalle_alquiler = new HashSet<detalle_alquiler>();
        }
    
        public int id_alquiler { get; set; }
        public Nullable<int> FK_id_cliente { get; set; }
        public Nullable<int> FK_id_empleado { get; set; }
        public System.DateTime fecha_inicio { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual ICollection<detalle_alquiler> detalle_alquiler { get; set; }
    }
}
