//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineClub_TuPeliculaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ciudad
    {
        public ciudad()
        {
            this.direccion_cliente = new HashSet<direccion_cliente>();
        }
    
        public int id_ciudad { get; set; }
        public string nom_ciudad { get; set; }
        public string cod_postal { get; set; }
    
        public virtual ICollection<direccion_cliente> direccion_cliente { get; set; }
    }
}
