//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineClub_TuPeliculaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public cliente()
        {
            this.alquiler = new HashSet<alquiler>();
            this.cliente1 = new HashSet<cliente>();
            this.detalle_alquiler = new HashSet<detalle_alquiler>();
            this.direccion_cliente = new HashSet<direccion_cliente>();
            this.telefono_cliente = new HashSet<telefono_cliente>();
        }
    
        public int id_cliente { get; set; }
        public string nroDocCli { get; set; }
        public string nombre { get; set; }
        public string correo { get; set; }
        public Nullable<int> FK_id_genero { get; set; }
        public int FK_id_tipo_documento { get; set; }
        public Nullable<int> FK_id_aval { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual ICollection<alquiler> alquiler { get; set; }
        public virtual ICollection<cliente> cliente1 { get; set; }
        public virtual cliente cliente2 { get; set; }
        public virtual genero genero { get; set; }
        public virtual tipo_documento tipo_documento { get; set; }
        public virtual ICollection<detalle_alquiler> detalle_alquiler { get; set; }
        public virtual ICollection<direccion_cliente> direccion_cliente { get; set; }
        public virtual ICollection<telefono_cliente> telefono_cliente { get; set; }
    }
}
