//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineClub_TuPeliculaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_alquiler
    {
        public int id_detalle { get; set; }
        public Nullable<int> FK_alquiler { get; set; }
        public Nullable<int> FK_id_cliente { get; set; }
        public Nullable<int> FK_id_ejemplar { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_devolucion { get; set; }
        public int dias_alquiler { get; set; }
    
        public virtual alquiler alquiler { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual ejemplar ejemplar { get; set; }
    }
}
