//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineClub_TuPeliculaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class direccion_cliente
    {
        public int id_direccion { get; set; }
        public Nullable<int> FK_id_cliente { get; set; }
        public Nullable<int> FK_id_ciudad { get; set; }
        public string direccion { get; set; }
        public string ciudad { get; set; }
    
        public virtual ciudad ciudad1 { get; set; }
        public virtual cliente cliente { get; set; }
    }
}
