//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineClub_TuPeliculaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class director
    {
        public director()
        {
            this.pelicula = new HashSet<pelicula>();
        }
    
        public int id_director { get; set; }
        public Nullable<int> FK_id_empleado { get; set; }
        public string nombre { get; set; }
        public string correo { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public Nullable<int> anios_experiencia { get; set; }
        public Nullable<int> nro_premios { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> FK_id_nacionalidad { get; set; }
    
        public virtual nacionalidad nacionalidad { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual ICollection<pelicula> pelicula { get; set; }
    }
}
