//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineClub_TuPeliculaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ejemplar
    {
        public ejemplar()
        {
            this.detalle_alquiler = new HashSet<detalle_alquiler>();
        }
    
        public int id_ejemplar { get; set; }
        public int FK_id_pelicula { get; set; }
        public Nullable<int> FK_id_empleado { get; set; }
        public int numero_ejemplar { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> FK_id_estado_conservacion { get; set; }
    
        public virtual ICollection<detalle_alquiler> detalle_alquiler { get; set; }
        public virtual pelicula pelicula { get; set; }
        public virtual estado_conservacion estado_conservacion { get; set; }
        public virtual empleado empleado { get; set; }
    }
}
