//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineClub_TuPeliculaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        public empleado()
        {
            this.alquiler = new HashSet<alquiler>();
            this.director = new HashSet<director>();
            this.ejemplar = new HashSet<ejemplar>();
            this.empleado1 = new HashSet<empleado>();
            this.pelicula = new HashSet<pelicula>();
            this.usuario_sistema = new HashSet<usuario_sistema>();
        }
    
        public int id_empleado { get; set; }
        public int FK_id_tipo_documento { get; set; }
        public Nullable<int> FK_id_empleado { get; set; }
        public string numero_documento { get; set; }
        public string nombre { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public Nullable<bool> activo { get; set; }
        public int FK_id_cargo { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public Nullable<decimal> salario { get; set; }
        public string correo { get; set; }
        public string telefono { get; set; }
        public Nullable<int> nro_hijos { get; set; }
    
        public virtual ICollection<alquiler> alquiler { get; set; }
        public virtual cargo cargo { get; set; }
        public virtual ICollection<director> director { get; set; }
        public virtual ICollection<ejemplar> ejemplar { get; set; }
        public virtual tipo_documento tipo_documento { get; set; }
        public virtual ICollection<empleado> empleado1 { get; set; }
        public virtual empleado empleado2 { get; set; }
        public virtual ICollection<pelicula> pelicula { get; set; }
        public virtual ICollection<usuario_sistema> usuario_sistema { get; set; }
    }
}
