//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineClub_TuPeliculaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class genero
    {
        public genero()
        {
            this.actor = new HashSet<actor>();
            this.cliente = new HashSet<cliente>();
        }
    
        public int id_genero { get; set; }
        public string nom_genero { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual ICollection<actor> actor { get; set; }
        public virtual ICollection<cliente> cliente { get; set; }
    }
}
