//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineClub_TuPeliculaAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_CineClub_TuPeliculaEntities : DbContext
    {
        public BD_CineClub_TuPeliculaEntities()
            : base("name=BD_CineClub_TuPeliculaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<actor> actor { get; set; }
        public DbSet<alquiler> alquiler { get; set; }
        public DbSet<cargo> cargo { get; set; }
        public DbSet<ciudad> ciudad { get; set; }
        public DbSet<cliente> cliente { get; set; }
        public DbSet<direccion_cliente> direccion_cliente { get; set; }
        public DbSet<director> director { get; set; }
        public DbSet<ejemplar> ejemplar { get; set; }
        public DbSet<empleado> empleado { get; set; }
        public DbSet<estado_conservacion> estado_conservacion { get; set; }
        public DbSet<genero> genero { get; set; }
        public DbSet<nacionalidad> nacionalidad { get; set; }
        public DbSet<papel> papel { get; set; }
        public DbSet<pelicula> pelicula { get; set; }
        public DbSet<pelicula_actor> pelicula_actor { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<telefono_cliente> telefono_cliente { get; set; }
        public DbSet<tipo_documento> tipo_documento { get; set; }
        public DbSet<tipo_telefono> tipo_telefono { get; set; }
        public DbSet<usuario_sistema> usuario_sistema { get; set; }
        public DbSet<detalle_alquiler> detalle_alquiler { get; set; }
    }
}
