//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineClub_TuPeliculaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nacionalidad
    {
        public nacionalidad()
        {
            this.actor = new HashSet<actor>();
            this.director = new HashSet<director>();
            this.pelicula = new HashSet<pelicula>();
        }
    
        public int id_nacionalidad { get; set; }
        public string pais { get; set; }
    
        public virtual ICollection<actor> actor { get; set; }
        public virtual ICollection<director> director { get; set; }
        public virtual ICollection<pelicula> pelicula { get; set; }
    }
}
