//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineClub_TuPeliculaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class papel
    {
        public papel()
        {
            this.pelicula_actor = new HashSet<pelicula_actor>();
        }
    
        public int id_papel { get; set; }
        public string nom_papel { get; set; }
    
        public virtual ICollection<pelicula_actor> pelicula_actor { get; set; }
    }
}
