//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineClub_TuPeliculaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pelicula_actor
    {
        public int id_pelicula_actor { get; set; }
        public Nullable<int> FK_id_pelicula { get; set; }
        public Nullable<int> FK_id_actor { get; set; }
        public Nullable<int> FK_id_papel { get; set; }
        public string nombre_per { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual actor actor { get; set; }
        public virtual papel papel { get; set; }
        public virtual pelicula pelicula { get; set; }
    }
}
