//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineClub_TuPeliculaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pelicula
    {
        public pelicula()
        {
            this.ejemplar = new HashSet<ejemplar>();
            this.pelicula_actor = new HashSet<pelicula_actor>();
        }
    
        public int id_pelicula { get; set; }
        public Nullable<int> FK_id_empleado { get; set; }
        public Nullable<int> FK_id_nacionalidad { get; set; }
        public int FK_id_director { get; set; }
        public string titulo_original { get; set; }
        public string titulo { get; set; }
        public string productora { get; set; }
        public Nullable<System.DateTime> fecha_estreno { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual director director { get; set; }
        public virtual ICollection<ejemplar> ejemplar { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual nacionalidad nacionalidad { get; set; }
        public virtual ICollection<pelicula_actor> pelicula_actor { get; set; }
    }
}
