//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineClub_TuPeliculaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class telefono_cliente
    {
        public int id_telefono { get; set; }
        public Nullable<int> FK_id_cliente { get; set; }
        public Nullable<int> FK_id_tip_telefono { get; set; }
        public string telefono { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual tipo_telefono tipo_telefono { get; set; }
    }
}
