//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineClub_TuPeliculaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_telefono
    {
        public tipo_telefono()
        {
            this.telefono_cliente = new HashSet<telefono_cliente>();
        }
    
        public int id_tip_telefono { get; set; }
        public string nom_tip_telefono { get; set; }
    
        public virtual ICollection<telefono_cliente> telefono_cliente { get; set; }
    }
}
