//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineClub_TuPeliculaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_documento
    {
        public tipo_documento()
        {
            this.cliente = new HashSet<cliente>();
            this.empleado = new HashSet<empleado>();
        }
    
        public int id_tipo_documento { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<cliente> cliente { get; set; }
        public virtual ICollection<empleado> empleado { get; set; }
    }
}
